export LOGURU_FORMAT='<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <cyan>{thread}</cyan>:<cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>'
export AWS_ACCESS_KEY_ID="AKIAXJWPWGFXJSGWMXKN"
export AWS_SECRET_ACCESS_KEY="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"
export EWOC_S3_SECRET_ACCESS_KEY="8hyE5d/Ge6E5vTZZ6FP95M64TbgDiBYoMfZlsouT"
export EWOC_S3_ACCESS_KEY_ID="AKIAXJWPWGFXJSGWMXKN"
export EWOC_CLOUD_PROVIDER=aws
export EWOC_BLOCKSIZE=1024
export GDAL_CACHEMAX=2000
export AGERA5_BUCKET=ewoc-agera5-yearly
export LOCAL_MODELS=True
export EWOC_MODELS_DIR_ROOT="/home/rbuguetd/dev/aux_data/"
export EWOC_REGION_NAME=eu-central-1
export EWOC_ENDPOINT_URL=s3.amazonaws.com
export EWOC_AUXDATA="/home/rbuguetd/dev/aux_data/"
export EWOC_TEST_VAL_TEST=False
export EWOC_TEST_DEBUG_MODE=True
